Added Delete Functionality
application-research/estuary-www pull request #126
Opened 2022-12-07 14:36 UTC by OlypsisAli

Previously, users were unable to delete files via the estuary dashboard. They now have that ability.

2022-12-07 14:39 UTC, OlypsisAli commented
@jimmylee Note that I decided to repull the latest code and reimplement my previous PR. Let me know if you have any feedback.

2022-12-07 16:50 UTC, neelvirdy commented on components/FilesTable.tsx
> +        accessor: (data) => String(data.id).padStart(9, '0'),
can just return `data.id` here

2022-12-07 16:50 UTC, neelvirdy commented on components/FilesTable.tsx
> +        maxWidth: '9%',
maxWidth isn't needed

2022-12-07 16:52 UTC, neelvirdy commented on components/FilesTable.tsx
> +const FilesTable = ({ files, setFiles }) => {
nit: `setFiles` -> `onDelete`

2022-12-07 16:56 UTC, neelvirdy commented
Thanks for opening a PR @OlypsisAli. The complexity here is that many files are no longer safely deletable. If they have entered the dealmaking stage, we can't allow a delete because it would break dealmaking for that file and all other files aggregated with it.

The only case you can safely delete in is when the file is still in a staging bucket that has not been aggregated. Instead of putting the delete button here and returning errors in all other cases, can you move the delete button into the StagingTable?

2022-12-07 17:50 UTC, gmelodie requested changes
Tiny comment. Other than that I really like your PR!! Thank you for doing this :)

2022-12-07 17:54 UTC, alvin-reyes commented on components/FilesTable.tsx
> +  const [gateway, setGateway] = useState('https://api.estuary.tech/gw/ipfs/');
yes the `gateway.estuary.tech` is peered with the API and shuttles so we can use it similar to how we use dweb and our api node so let's use `https://gateway.estuary.tech/gw/ipfs/` instead.

Some examples:

- https://gateway.estuary.tech/gw/ipfs/bafybeigvgzoolc3drupxhlevdp2ugqcrbcsqfmcek2zxiw5wctk3xjpjwy
- https://gateway.estuary.tech/gw/ipfs/QmPBHAjRLZqvJwcBUTiVxNtvugToAnTyJxpzTCgKZVHsvw

2022-12-07 19:00 UTC, neelvirdy commented
> @neelvirdy this seems like an estuary problem, not a frontend one. I mean, nothing stops me from deleting a file while deal making is in process if I just call the API. I think just unpinning the CIDs is good enough in terms of deletion.

in dealmaking and reconciliation, we dont handle the cases where data has been deleted yet - so we just prevent it if we've entered those stages

so you can call the API but it will throw an error if it's a content that's been aggregated in a zone and that zone has started dealmaking. instead of setting up the user to hit the error pretty often in the frontend, i'd rather put it in a page (Staging) where all of the files are in a state that will not lead to an API error

2023-01-13 05:26 UTC, jimmylee commented
Going to close this since its lingered for a while, feel free to re-open when you've had a chance to work through our comments.

2023-01-13 05:26 UTC, closed without merging