Added Delete functionality to home page
application-research/estuary-www pull request #82
Opened 2022-10-20 19:04 UTC by OlypsisAli

Previously users could note delete files uploaded to estuary via the dashboard. They now have this ability.

2022-10-20 19:43 UTC, jimmylee requested changes
Some minor nits, also make sure you have `prettier`, thank you jumping in like this @OlypsisAli

2022-10-20 19:43 UTC, jimmylee commented on README.md
> +$ c
Wait whats this?

2022-10-20 19:43 UTC, jimmylee commented on components/FilesTable.tsx
> +              htmlFor="FILE_UPLOAD_TARGET"
I think this ` htmlFor` should be removed, it doesn't belong here

2022-10-20 21:46 UTC, OlypsisAli commented
Forgot to add prettier. Will do so when I step back in.

2022-11-11 11:26 UTC, jimmylee commented
Needs to fix conflict

2022-11-19 22:53 UTC, jimmylee commented
Closing this until you have a chance to fix conflicts

2022-11-19 22:53 UTC, closed without merging

2022-11-29 13:10 UTC, OlypsisAli commented
@jimmylee Was on a family vacation for the past few weeks. Will get this fixed up.